modLoader="javafml"
loaderVersion="[37,)"
license="GPLv3"
issueTrackerURL="https://github.com/Skizzium/Project-Apple/issues"
[[mods]]
modId="skizzik"
version="${file.jarVersion}"
displayName="Skizzik & Co. [Project Apple]"
#updateJSONURL=""
displayURL="https://skizzium.com/"
logoFile="logo.png"
credits="Credits to diesieben07 (skulls and custom boss bar) and all the helpful people in the forge community for putting up with my stupidity and helping me out. \nAlso, Skizzik & Spookzik themes are both from the Terraria OST. Nightmare Spookzik's theme is the well-known Doom theme (The Only Thing they Fear is You). These are all temporary solutions until I finally make my own themes."
authors="\n- Skizzium [Ownership], \n- uSkizzik [Coding & Concepts], \n- LazTheArtist [Assets & Coding], \n- PRO#6639 [Ukrainian Translations]"
description='''
From seemingly harmless candies and rainbows, to dark back stories, suffering mutants, distant Wither relatives and multiversal aliens this mod adds a lot of dimensions, boss battles and structures.
'''
[[dependencies.skizzik]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.skizzik]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
