modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved"

[[mods]]
modId="skizzik"
version="Skizzik [1.8.0 - Beta #5]"
displayName="Skizzik"
credits="Boss Music is from Terraria"
displayURL="https://skizzik-industries.xyz"
logoFile="logo.png"
authors="uSkizzik"
description='''
Coming Soon
'''

[[dependencies.skizzik]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




